apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: petshop-api
  name: petshop-api
spec:
  replicas: 1
  selector:
    matchLabels:
      run: petshop-api
  strategy: {}
  template:
    metadata:
      labels:
        run: petshop-api
    spec:
      containers:
        - image: petshop-api-image # image name updated by Makefile
          name: petshop-api
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_password
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: hostname-config
                  key: postgres_host
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: petshop-api
  name: petshop-api
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    run: petshop-api
  type: LoadBalancer
